#pragma once

#include "Any.h"
#include "Type/TypeBase.h"
#include "Type/Property/Property.h"
#include "Type/Property/BoolProperpty.h"
#include "Type/Property/StringProperty.h"
#include "Type/Property/IntegerProperpty.h"
#include "Type/Property/EnumProperty.h"
#include "Type/ClassType.h"
#include "Type/BoolType.h"
#include "Type/StringType.h"
#include "Type/IntegerType.h"
#include "Type/EnumType.h"
#include "Type/FloatType.h"
#include "Factory/TypeFactory.h"
#include "Factory/PropertyFactory.h"
#include "Utils/VariableTraits.hpp"
#include "CastOp.hpp"

